### ISSUE TITLE
Failed to find old commit hashes

### ISSUE THREAD

**Issue by Assem-Uber** [tiged/tiged#93] opened 2024-06-19 12:17 UTC
Tiged fails to find any commit other than the latest one.

Example, i'm running the following command:
`npx --yes tiged https://github.com/uber/cadence-idl#83d5cae7fc5176f73486ffe82144044711930073 cadence-idl`

While the commit is there, i get this error:
`! could not find commit hash for 83d5cae7fc5176f73486ffe82144044711930073`

**Comment by nake89** [comment] 2024-08-09 09:49
Seems to be duplicate of https://github.com/tiged/tiged/issues/90. There is a PR. Will get fixed after PR gets merged.

**Closed by nake89** 2024-08-09 09:49 UTC
